//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesParser.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainRuleExample
    {
        public int mainRuleExampleID { get; set; }
        public int mainRuleId { get; set; }
        public string exampleText { get; set; }
    
        public virtual MainRule MainRule { get; set; }
    }
}
