//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesParser.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainRule
    {
        public MainRule()
        {
            this.MainRuleExamples = new HashSet<MainRuleExample>();
            this.SubRules = new HashSet<SubRule>();
        }
    
        public int mainRuleID { get; set; }
        public int sectionID { get; set; }
        public int mainRuleNumber { get; set; }
        public string ruleText { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<MainRuleExample> MainRuleExamples { get; set; }
        public virtual ICollection<SubRule> SubRules { get; set; }
    }
}
