//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesParser.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRule
    {
        public SubRule()
        {
            this.SubRuleExamples = new HashSet<SubRuleExample>();
        }
    
        public int subRuleID { get; set; }
        public int mainRuleId { get; set; }
        public int subRuleLetter { get; set; }
        public string ruleText { get; set; }
    
        public virtual MainRule MainRule { get; set; }
        public virtual ICollection<SubRuleExample> SubRuleExamples { get; set; }
    }
}
