//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesParser.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSection
    {
        public SubSection()
        {
            this.MainRules = new HashSet<MainRule>();
        }
    
        public int subSectionID { get; set; }
        public int sectionID { get; set; }
        public int subSectionNumber { get; set; }
        public string subSectionName { get; set; }
    
        public virtual ICollection<MainRule> MainRules { get; set; }
        public virtual Section Section { get; set; }
    }
}
